spring.application.name=ForTheWater

app:
overpass:
url: "http://overpass-api.de/api/interpreter"
search-radius: 1000 # meters
copernicus:
stat-api-url: "https://sh.dataspace.copernicus.eu/api/v1/statistics"
client-id: "YOUR_COPERNICUS_CLIENT_ID" # Get this from their portal
client-secret: "YOUR_COPERNICUS_SECRET"
